// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_token.sql

package storedb

import (
	"context"
	"time"
)

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
DELETE FROM api_token
WHERE id = 1
  AND row_version = ?1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, expectedRowVersion int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIToken, expectedRowVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, token_hash, token_hint, created_at, updated_at, row_version, token_secret
FROM api_token
WHERE id = 1
`

func (q *Queries) GetAPIToken(ctx context.Context) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPIToken)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenHint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
		&i.TokenSecret,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :exec
INSERT INTO api_token (
    id,
    token_hash,
    token_hint,
    token_secret,
    created_at,
    updated_at,
    row_version
) VALUES (
    1,
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    0
)
`

type InsertAPITokenParams struct {
	TokenHash   []byte    `json:"token_hash"`
	TokenHint   string    `json:"token_hint"`
	TokenSecret string    `json:"token_secret"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIToken,
		arg.TokenHash,
		arg.TokenHint,
		arg.TokenSecret,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
