// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_token.sql

package storedb

import (
	"context"
	"time"
)

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
DELETE FROM api_token
WHERE id = 1
  AND row_version = ?1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, expectedRowVersion int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIToken, expectedRowVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, token_hash, token_hint, created_at, updated_at, row_version
FROM api_token
WHERE id = 1
`

func (q *Queries) GetAPIToken(ctx context.Context) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPIToken)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenHint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :exec
INSERT INTO api_token (
    id,
    token_hash,
    token_hint,
    created_at,
    updated_at,
    row_version
) VALUES (
    1,
    ?1,
    ?2,
    ?3,
    ?4,
    0
)
`

type InsertAPITokenParams struct {
	TokenHash []byte    `json:"token_hash"`
	TokenHint string    `json:"token_hint"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIToken,
		arg.TokenHash,
		arg.TokenHint,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateAPIToken = `-- name: UpdateAPIToken :execrows
UPDATE api_token
SET
    token_hash = ?1,
    token_hint = ?2,
    updated_at = ?3,
    row_version = row_version + 1
WHERE id = 1
  AND row_version = ?4
`

type UpdateAPITokenParams struct {
	TokenHash          []byte    `json:"token_hash"`
	TokenHint          string    `json:"token_hint"`
	UpdatedAt          time.Time `json:"updated_at"`
	ExpectedRowVersion int64     `json:"expected_row_version"`
}

func (q *Queries) UpdateAPIToken(ctx context.Context, arg UpdateAPITokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAPIToken,
		arg.TokenHash,
		arg.TokenHint,
		arg.UpdatedAt,
		arg.ExpectedRowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
