// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package storedb

import (
	"context"
	"time"
)

const getCategory = `-- name: GetCategory :one
SELECT name, cloud_path, save_path, enabled, created_at, updated_at
FROM categories
WHERE name = ?1
`

func (q *Queries) GetCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, name)
	var i Category
	err := row.Scan(
		&i.Name,
		&i.CloudPath,
		&i.SavePath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT name, cloud_path, save_path, enabled, created_at, updated_at
FROM categories
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.Name,
			&i.CloudPath,
			&i.SavePath,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategory = `-- name: UpsertCategory :one
INSERT INTO categories (
    name,
    cloud_path,
    save_path,
    enabled,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
ON CONFLICT (name) DO UPDATE SET
    cloud_path = excluded.cloud_path,
    save_path = excluded.save_path,
    enabled = excluded.enabled,
    updated_at = excluded.updated_at
RETURNING name, cloud_path, save_path, enabled, created_at, updated_at
`

type UpsertCategoryParams struct {
	Name      string    `json:"name"`
	CloudPath string    `json:"cloud_path"`
	SavePath  string    `json:"save_path"`
	Enabled   int64     `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, upsertCategory,
		arg.Name,
		arg.CloudPath,
		arg.SavePath,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.Name,
		&i.CloudPath,
		&i.SavePath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
