// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package storedb

import (
	"context"
	"database/sql"
	"time"
)

const claimDue = `-- name: ClaimDue :one
UPDATE downloads
SET
    lease_owner = ?1,
    lease_until = ?2,
    row_version = row_version + 1
WHERE hash = (
    SELECT candidate.hash
    FROM downloads AS candidate
    WHERE candidate.next_run_at <= ?3
      AND candidate.state NOT IN ('COMPLETED', 'FAILED', 'CANCELLED', 'DELETED')
      AND (candidate.lease_until IS NULL OR candidate.lease_until <= ?3)
    ORDER BY candidate.next_run_at ASC, candidate.created_at ASC, candidate.hash ASC
    LIMIT 1
)
RETURNING hash, name, source_kind, submission_uri, category, cloud_folder, save_path, destination_name, cloud_task_name, cloud_source_path, content_path, is_multi_file, total_size, state, offline_progress, copy_progress, qbit_progress, last_upstream_status, last_error, phase_started_at, next_run_at, lease_until, lease_owner, attempt_count, delete_files_requested, created_at, updated_at, completed_at, removed_at, row_version, pause_requested, last_error_code
`

type ClaimDueParams struct {
	Owner      sql.NullString `json:"owner"`
	LeaseUntil sql.NullTime   `json:"lease_until"`
	Now        sql.NullTime   `json:"now"`
}

func (q *Queries) ClaimDue(ctx context.Context, arg ClaimDueParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, claimDue, arg.Owner, arg.LeaseUntil, arg.Now)
	var i Download
	err := row.Scan(
		&i.Hash,
		&i.Name,
		&i.SourceKind,
		&i.SubmissionUri,
		&i.Category,
		&i.CloudFolder,
		&i.SavePath,
		&i.DestinationName,
		&i.CloudTaskName,
		&i.CloudSourcePath,
		&i.ContentPath,
		&i.IsMultiFile,
		&i.TotalSize,
		&i.State,
		&i.OfflineProgress,
		&i.CopyProgress,
		&i.QbitProgress,
		&i.LastUpstreamStatus,
		&i.LastError,
		&i.PhaseStartedAt,
		&i.NextRunAt,
		&i.LeaseUntil,
		&i.LeaseOwner,
		&i.AttemptCount,
		&i.DeleteFilesRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RemovedAt,
		&i.RowVersion,
		&i.PauseRequested,
		&i.LastErrorCode,
	)
	return i, err
}

const commitClaim = `-- name: CommitClaim :execrows
UPDATE downloads
SET
    name = ?1,
    destination_name = ?2,
    cloud_task_name = ?3,
    cloud_source_path = ?4,
    content_path = ?5,
    is_multi_file = ?6,
    total_size = ?7,
    state = ?8,
    offline_progress = ?9,
    copy_progress = ?10,
    qbit_progress = ?11,
    last_upstream_status = ?12,
    last_error = ?13,
    last_error_code = ?14,
    phase_started_at = ?15,
    next_run_at = ?16,
    attempt_count = ?17,
    delete_files_requested = ?18,
    pause_requested = ?19,
    updated_at = ?20,
    completed_at = ?21,
    removed_at = ?22,
    lease_until = NULL,
    lease_owner = NULL,
    row_version = row_version + 1
WHERE hash = ?23
  AND state = ?24
  AND lease_owner = ?25
  AND row_version = ?26
`

type CommitClaimParams struct {
	Name                 string         `json:"name"`
	DestinationName      sql.NullString `json:"destination_name"`
	CloudTaskName        sql.NullString `json:"cloud_task_name"`
	CloudSourcePath      sql.NullString `json:"cloud_source_path"`
	ContentPath          sql.NullString `json:"content_path"`
	IsMultiFile          sql.NullInt64  `json:"is_multi_file"`
	TotalSize            int64          `json:"total_size"`
	State                string         `json:"state"`
	OfflineProgress      float64        `json:"offline_progress"`
	CopyProgress         float64        `json:"copy_progress"`
	QbitProgress         float64        `json:"qbit_progress"`
	LastUpstreamStatus   sql.NullString `json:"last_upstream_status"`
	LastError            sql.NullString `json:"last_error"`
	LastErrorCode        sql.NullString `json:"last_error_code"`
	PhaseStartedAt       time.Time      `json:"phase_started_at"`
	NextRunAt            sql.NullTime   `json:"next_run_at"`
	AttemptCount         int64          `json:"attempt_count"`
	DeleteFilesRequested int64          `json:"delete_files_requested"`
	PauseRequested       int64          `json:"pause_requested"`
	UpdatedAt            time.Time      `json:"updated_at"`
	CompletedAt          sql.NullTime   `json:"completed_at"`
	RemovedAt            sql.NullTime   `json:"removed_at"`
	Hash                 string         `json:"hash"`
	ExpectedState        string         `json:"expected_state"`
	LeaseOwner           sql.NullString `json:"lease_owner"`
	ExpectedRowVersion   int64          `json:"expected_row_version"`
}

func (q *Queries) CommitClaim(ctx context.Context, arg CommitClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, commitClaim,
		arg.Name,
		arg.DestinationName,
		arg.CloudTaskName,
		arg.CloudSourcePath,
		arg.ContentPath,
		arg.IsMultiFile,
		arg.TotalSize,
		arg.State,
		arg.OfflineProgress,
		arg.CopyProgress,
		arg.QbitProgress,
		arg.LastUpstreamStatus,
		arg.LastError,
		arg.LastErrorCode,
		arg.PhaseStartedAt,
		arg.NextRunAt,
		arg.AttemptCount,
		arg.DeleteFilesRequested,
		arg.PauseRequested,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.RemovedAt,
		arg.Hash,
		arg.ExpectedState,
		arg.LeaseOwner,
		arg.ExpectedRowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
