// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package storedb

import (
	"context"
	"database/sql"
	"time"
)

const cancelDownload = `-- name: CancelDownload :execrows
UPDATE downloads
SET
    state = 'CANCEL_REQUESTED',
    pause_requested = 0,
    phase_started_at = ?1,
    next_run_at = ?1,
    updated_at = ?1,
    row_version = row_version + 1
WHERE hash = ?2
  AND state IN (
      'ACCEPTED',
      'STOPPED',
      'SUBMITTING_OFFLINE',
      'WAITING_OFFLINE',
      'SUBMITTING_COPY',
      'WAITING_COPY',
      'VERIFYING_LOCAL'
  )
`

type CancelDownloadParams struct {
	Now  time.Time `json:"now"`
	Hash string    `json:"hash"`
}

func (q *Queries) CancelDownload(ctx context.Context, arg CancelDownloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelDownload, arg.Now, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDownloadFiles = `-- name: DeleteDownloadFiles :exec
DELETE FROM download_files
WHERE download_hash = ?1
`

func (q *Queries) DeleteDownloadFiles(ctx context.Context, downloadHash string) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadFiles, downloadHash)
	return err
}

const getDownload = `-- name: GetDownload :one
SELECT hash, name, source_kind, submission_uri, category, cloud_folder, save_path, destination_name, cloud_task_name, cloud_result_path, content_path, is_multi_file, total_size, state, offline_progress, copy_progress, qbit_progress, last_upstream_status, last_error, phase_started_at, next_run_at, lease_until, lease_owner, attempt_count, delete_files_requested, created_at, updated_at, completed_at, removed_at, row_version, pause_requested, last_error_code, offline_started_at, copy_completed_at, copy_source_path, tags, auto_tmm, name_overridden
FROM downloads
WHERE hash = ?1
`

func (q *Queries) GetDownload(ctx context.Context, hash string) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownload, hash)
	var i Download
	err := row.Scan(
		&i.Hash,
		&i.Name,
		&i.SourceKind,
		&i.SubmissionUri,
		&i.Category,
		&i.CloudFolder,
		&i.SavePath,
		&i.DestinationName,
		&i.CloudTaskName,
		&i.CloudResultPath,
		&i.ContentPath,
		&i.IsMultiFile,
		&i.TotalSize,
		&i.State,
		&i.OfflineProgress,
		&i.CopyProgress,
		&i.QbitProgress,
		&i.LastUpstreamStatus,
		&i.LastError,
		&i.PhaseStartedAt,
		&i.NextRunAt,
		&i.LeaseUntil,
		&i.LeaseOwner,
		&i.AttemptCount,
		&i.DeleteFilesRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RemovedAt,
		&i.RowVersion,
		&i.PauseRequested,
		&i.LastErrorCode,
		&i.OfflineStartedAt,
		&i.CopyCompletedAt,
		&i.CopySourcePath,
		&i.Tags,
		&i.AutoTmm,
		&i.NameOverridden,
	)
	return i, err
}

const insertDownload = `-- name: InsertDownload :exec
INSERT INTO downloads (
    hash,
    name,
    source_kind,
    submission_uri,
    category,
    tags,
    auto_tmm,
    name_overridden,
    cloud_folder,
    save_path,
    destination_name,
    cloud_task_name,
    cloud_result_path,
    copy_source_path,
    content_path,
    is_multi_file,
    total_size,
    state,
    offline_progress,
    copy_progress,
    qbit_progress,
    last_upstream_status,
    last_error,
    last_error_code,
    phase_started_at,
    offline_started_at,
    copy_completed_at,
    next_run_at,
    lease_until,
    lease_owner,
    attempt_count,
    delete_files_requested,
    created_at,
    updated_at,
    completed_at,
    removed_at,
    row_version
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18,
    ?19,
    ?20,
    ?21,
    ?22,
    ?23,
    ?24,
    ?25,
    ?26,
    ?27,
    ?28,
    ?29,
    ?30,
    ?31,
    ?32,
    ?33,
    ?34,
    ?35,
    ?36,
    ?37
)
`

type InsertDownloadParams struct {
	Hash                 string         `json:"hash"`
	Name                 string         `json:"name"`
	SourceKind           string         `json:"source_kind"`
	SubmissionUri        string         `json:"submission_uri"`
	Category             string         `json:"category"`
	Tags                 string         `json:"tags"`
	AutoTmm              int64          `json:"auto_tmm"`
	NameOverridden       int64          `json:"name_overridden"`
	CloudFolder          string         `json:"cloud_folder"`
	SavePath             string         `json:"save_path"`
	DestinationName      sql.NullString `json:"destination_name"`
	CloudTaskName        sql.NullString `json:"cloud_task_name"`
	CloudResultPath      sql.NullString `json:"cloud_result_path"`
	CopySourcePath       sql.NullString `json:"copy_source_path"`
	ContentPath          sql.NullString `json:"content_path"`
	IsMultiFile          sql.NullInt64  `json:"is_multi_file"`
	TotalSize            int64          `json:"total_size"`
	State                string         `json:"state"`
	OfflineProgress      float64        `json:"offline_progress"`
	CopyProgress         float64        `json:"copy_progress"`
	QbitProgress         float64        `json:"qbit_progress"`
	LastUpstreamStatus   sql.NullString `json:"last_upstream_status"`
	LastError            sql.NullString `json:"last_error"`
	LastErrorCode        sql.NullString `json:"last_error_code"`
	PhaseStartedAt       time.Time      `json:"phase_started_at"`
	OfflineStartedAt     sql.NullTime   `json:"offline_started_at"`
	CopyCompletedAt      sql.NullTime   `json:"copy_completed_at"`
	NextRunAt            sql.NullTime   `json:"next_run_at"`
	LeaseUntil           sql.NullTime   `json:"lease_until"`
	LeaseOwner           sql.NullString `json:"lease_owner"`
	AttemptCount         int64          `json:"attempt_count"`
	DeleteFilesRequested int64          `json:"delete_files_requested"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	CompletedAt          sql.NullTime   `json:"completed_at"`
	RemovedAt            sql.NullTime   `json:"removed_at"`
	RowVersion           int64          `json:"row_version"`
}

func (q *Queries) InsertDownload(ctx context.Context, arg InsertDownloadParams) error {
	_, err := q.db.ExecContext(ctx, insertDownload,
		arg.Hash,
		arg.Name,
		arg.SourceKind,
		arg.SubmissionUri,
		arg.Category,
		arg.Tags,
		arg.AutoTmm,
		arg.NameOverridden,
		arg.CloudFolder,
		arg.SavePath,
		arg.DestinationName,
		arg.CloudTaskName,
		arg.CloudResultPath,
		arg.CopySourcePath,
		arg.ContentPath,
		arg.IsMultiFile,
		arg.TotalSize,
		arg.State,
		arg.OfflineProgress,
		arg.CopyProgress,
		arg.QbitProgress,
		arg.LastUpstreamStatus,
		arg.LastError,
		arg.LastErrorCode,
		arg.PhaseStartedAt,
		arg.OfflineStartedAt,
		arg.CopyCompletedAt,
		arg.NextRunAt,
		arg.LeaseUntil,
		arg.LeaseOwner,
		arg.AttemptCount,
		arg.DeleteFilesRequested,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.RemovedAt,
		arg.RowVersion,
	)
	return err
}

const insertDownloadFile = `-- name: InsertDownloadFile :exec
INSERT INTO download_files (
    download_hash,
    file_index,
    relative_path,
    size
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type InsertDownloadFileParams struct {
	DownloadHash string `json:"download_hash"`
	FileIndex    int64  `json:"file_index"`
	RelativePath string `json:"relative_path"`
	Size         int64  `json:"size"`
}

func (q *Queries) InsertDownloadFile(ctx context.Context, arg InsertDownloadFileParams) error {
	_, err := q.db.ExecContext(ctx, insertDownloadFile,
		arg.DownloadHash,
		arg.FileIndex,
		arg.RelativePath,
		arg.Size,
	)
	return err
}

const listAllVisibleDownloads = `-- name: ListAllVisibleDownloads :many
SELECT hash, name, source_kind, submission_uri, category, cloud_folder, save_path, destination_name, cloud_task_name, cloud_result_path, content_path, is_multi_file, total_size, state, offline_progress, copy_progress, qbit_progress, last_upstream_status, last_error, phase_started_at, next_run_at, lease_until, lease_owner, attempt_count, delete_files_requested, created_at, updated_at, completed_at, removed_at, row_version, pause_requested, last_error_code, offline_started_at, copy_completed_at, copy_source_path, tags, auto_tmm, name_overridden
FROM downloads
WHERE removed_at IS NULL OR (state = 'DELETE_REQUESTED' AND last_error IS NOT NULL)
ORDER BY created_at DESC, hash ASC
`

func (q *Queries) ListAllVisibleDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listAllVisibleDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.Hash,
			&i.Name,
			&i.SourceKind,
			&i.SubmissionUri,
			&i.Category,
			&i.CloudFolder,
			&i.SavePath,
			&i.DestinationName,
			&i.CloudTaskName,
			&i.CloudResultPath,
			&i.ContentPath,
			&i.IsMultiFile,
			&i.TotalSize,
			&i.State,
			&i.OfflineProgress,
			&i.CopyProgress,
			&i.QbitProgress,
			&i.LastUpstreamStatus,
			&i.LastError,
			&i.PhaseStartedAt,
			&i.NextRunAt,
			&i.LeaseUntil,
			&i.LeaseOwner,
			&i.AttemptCount,
			&i.DeleteFilesRequested,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RemovedAt,
			&i.RowVersion,
			&i.PauseRequested,
			&i.LastErrorCode,
			&i.OfflineStartedAt,
			&i.CopyCompletedAt,
			&i.CopySourcePath,
			&i.Tags,
			&i.AutoTmm,
			&i.NameOverridden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadFiles = `-- name: ListDownloadFiles :many
SELECT download_hash, file_index, relative_path, size
FROM download_files
WHERE download_hash = ?1
ORDER BY file_index ASC
`

func (q *Queries) ListDownloadFiles(ctx context.Context, downloadHash string) ([]DownloadFile, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadFiles, downloadHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadFile{}
	for rows.Next() {
		var i DownloadFile
		if err := rows.Scan(
			&i.DownloadHash,
			&i.FileIndex,
			&i.RelativePath,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleDownloads = `-- name: ListVisibleDownloads :many
SELECT hash, name, source_kind, submission_uri, category, cloud_folder, save_path, destination_name, cloud_task_name, cloud_result_path, content_path, is_multi_file, total_size, state, offline_progress, copy_progress, qbit_progress, last_upstream_status, last_error, phase_started_at, next_run_at, lease_until, lease_owner, attempt_count, delete_files_requested, created_at, updated_at, completed_at, removed_at, row_version, pause_requested, last_error_code, offline_started_at, copy_completed_at, copy_source_path, tags, auto_tmm, name_overridden
FROM downloads
WHERE category = ?1
  AND (removed_at IS NULL OR (state = 'DELETE_REQUESTED' AND last_error IS NOT NULL))
ORDER BY created_at DESC, hash ASC
`

func (q *Queries) ListVisibleDownloads(ctx context.Context, category string) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleDownloads, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.Hash,
			&i.Name,
			&i.SourceKind,
			&i.SubmissionUri,
			&i.Category,
			&i.CloudFolder,
			&i.SavePath,
			&i.DestinationName,
			&i.CloudTaskName,
			&i.CloudResultPath,
			&i.ContentPath,
			&i.IsMultiFile,
			&i.TotalSize,
			&i.State,
			&i.OfflineProgress,
			&i.CopyProgress,
			&i.QbitProgress,
			&i.LastUpstreamStatus,
			&i.LastError,
			&i.PhaseStartedAt,
			&i.NextRunAt,
			&i.LeaseUntil,
			&i.LeaseOwner,
			&i.AttemptCount,
			&i.DeleteFilesRequested,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RemovedAt,
			&i.RowVersion,
			&i.PauseRequested,
			&i.LastErrorCode,
			&i.OfflineStartedAt,
			&i.CopyCompletedAt,
			&i.CopySourcePath,
			&i.Tags,
			&i.AutoTmm,
			&i.NameOverridden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDue = `-- name: NextDue :one
SELECT effective_due.next_due
FROM (
    SELECT candidate.next_run_at AS next_due
    FROM downloads AS candidate
    WHERE candidate.state NOT IN ('STOPPED', 'COMPLETED', 'FAILED', 'CANCELLED', 'DELETED')
      AND candidate.next_run_at IS NOT NULL
      AND (candidate.lease_until IS NULL OR candidate.lease_until <= ?1 OR candidate.lease_until <= candidate.next_run_at)

    UNION ALL

    SELECT candidate.lease_until AS next_due
    FROM downloads AS candidate
    WHERE candidate.state NOT IN ('STOPPED', 'COMPLETED', 'FAILED', 'CANCELLED', 'DELETED')
      AND candidate.next_run_at IS NOT NULL
      AND candidate.lease_until > ?1
      AND candidate.lease_until > candidate.next_run_at
) AS effective_due
ORDER BY effective_due.next_due ASC
LIMIT 1
`

func (q *Queries) NextDue(ctx context.Context, now sql.NullTime) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, nextDue, now)
	var next_due sql.NullTime
	err := row.Scan(&next_due)
	return next_due, err
}

const pauseDownload = `-- name: PauseDownload :execrows
UPDATE downloads
SET
    state = 'CANCEL_REQUESTED',
    pause_requested = 1,
    phase_started_at = ?1,
    next_run_at = ?1,
    updated_at = ?1,
    row_version = row_version + 1
WHERE hash = ?2
  AND state IN (
      'ACCEPTED',
      'SUBMITTING_OFFLINE',
      'WAITING_OFFLINE',
      'SUBMITTING_COPY',
      'WAITING_COPY',
      'VERIFYING_LOCAL'
  )
`

type PauseDownloadParams struct {
	Now  time.Time `json:"now"`
	Hash string    `json:"hash"`
}

func (q *Queries) PauseDownload(ctx context.Context, arg PauseDownloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pauseDownload, arg.Now, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestDelete = `-- name: RequestDelete :execrows
UPDATE downloads
SET
    state = 'DELETE_REQUESTED',
    pause_requested = 0,
    delete_files_requested = CASE
        WHEN delete_files_requested = 1 OR ?1 = 1 THEN 1
        ELSE 0
    END,
    phase_started_at = ?2,
    next_run_at = ?2,
    updated_at = ?2,
    removed_at = COALESCE(removed_at, ?2),
    row_version = row_version + 1
WHERE hash = ?3
  AND state != 'DELETED'
  AND (
      state != 'DELETE_REQUESTED'
      OR (?1 = 1 AND delete_files_requested = 0)
  )
`

type RequestDeleteParams struct {
	DeleteFilesRequested interface{} `json:"delete_files_requested"`
	Now                  time.Time   `json:"now"`
	Hash                 string      `json:"hash"`
}

func (q *Queries) RequestDelete(ctx context.Context, arg RequestDeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestDelete, arg.DeleteFilesRequested, arg.Now, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryCleanup = `-- name: RetryCleanup :execrows
UPDATE downloads
SET
    last_error = NULL,
    last_error_code = NULL,
    attempt_count = 0,
    phase_started_at = ?1,
    next_run_at = ?1,
    updated_at = ?1,
    row_version = row_version + 1
WHERE hash = ?2
  AND state IN ('CANCEL_REQUESTED', 'DELETE_REQUESTED')
  AND last_error IS NOT NULL
`

type RetryCleanupParams struct {
	Now  time.Time `json:"now"`
	Hash string    `json:"hash"`
}

func (q *Queries) RetryCleanup(ctx context.Context, arg RetryCleanupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryCleanup, arg.Now, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryDownload = `-- name: RetryDownload :execrows
UPDATE downloads
SET
    state = ?1,
    copy_source_path = CASE
        WHEN ?1 = 'SUBMITTING_COPY' AND last_error_code = 'destination_conflict' THEN NULL
        ELSE copy_source_path
    END,
    destination_name = CASE
        WHEN ?1 = 'SUBMITTING_COPY' AND last_error_code = 'destination_conflict' THEN NULL
        ELSE destination_name
    END,
    last_error = NULL,
    last_error_code = NULL,
    attempt_count = 0,
    phase_started_at = ?2,
    next_run_at = ?2,
    lease_until = NULL,
    lease_owner = NULL,
    updated_at = ?2,
    row_version = row_version + 1
WHERE hash = ?3
  AND state = 'FAILED'
`

type RetryDownloadParams struct {
	State string    `json:"state"`
	Now   time.Time `json:"now"`
	Hash  string    `json:"hash"`
}

func (q *Queries) RetryDownload(ctx context.Context, arg RetryDownloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryDownload, arg.State, arg.Now, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reviveDownload = `-- name: ReviveDownload :exec
UPDATE downloads
SET
    name = ?1,
    source_kind = ?2,
    submission_uri = ?3,
    category = ?4,
    tags = ?5,
    auto_tmm = ?6,
    name_overridden = ?7,
    cloud_folder = ?8,
    save_path = ?9,
    destination_name = ?10,
    cloud_task_name = ?11,
    cloud_result_path = ?12,
    copy_source_path = ?13,
    content_path = ?14,
    is_multi_file = ?15,
    total_size = ?16,
    state = ?17,
    offline_progress = ?18,
    copy_progress = ?19,
    qbit_progress = ?20,
    last_upstream_status = ?21,
    last_error = NULL,
    last_error_code = NULL,
    phase_started_at = ?22,
    offline_started_at = ?23,
    copy_completed_at = ?24,
    next_run_at = ?25,
    lease_until = NULL,
    lease_owner = NULL,
    attempt_count = 0,
    delete_files_requested = 0,
    pause_requested = 0,
    created_at = ?26,
    updated_at = ?27,
    completed_at = NULL,
    removed_at = NULL,
    row_version = row_version + 1
WHERE hash = ?28
  AND state = 'DELETED'
`

type ReviveDownloadParams struct {
	Name               string         `json:"name"`
	SourceKind         string         `json:"source_kind"`
	SubmissionUri      string         `json:"submission_uri"`
	Category           string         `json:"category"`
	Tags               string         `json:"tags"`
	AutoTmm            int64          `json:"auto_tmm"`
	NameOverridden     int64          `json:"name_overridden"`
	CloudFolder        string         `json:"cloud_folder"`
	SavePath           string         `json:"save_path"`
	DestinationName    sql.NullString `json:"destination_name"`
	CloudTaskName      sql.NullString `json:"cloud_task_name"`
	CloudResultPath    sql.NullString `json:"cloud_result_path"`
	CopySourcePath     sql.NullString `json:"copy_source_path"`
	ContentPath        sql.NullString `json:"content_path"`
	IsMultiFile        sql.NullInt64  `json:"is_multi_file"`
	TotalSize          int64          `json:"total_size"`
	State              string         `json:"state"`
	OfflineProgress    float64        `json:"offline_progress"`
	CopyProgress       float64        `json:"copy_progress"`
	QbitProgress       float64        `json:"qbit_progress"`
	LastUpstreamStatus sql.NullString `json:"last_upstream_status"`
	PhaseStartedAt     time.Time      `json:"phase_started_at"`
	OfflineStartedAt   sql.NullTime   `json:"offline_started_at"`
	CopyCompletedAt    sql.NullTime   `json:"copy_completed_at"`
	NextRunAt          sql.NullTime   `json:"next_run_at"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	Hash               string         `json:"hash"`
}

func (q *Queries) ReviveDownload(ctx context.Context, arg ReviveDownloadParams) error {
	_, err := q.db.ExecContext(ctx, reviveDownload,
		arg.Name,
		arg.SourceKind,
		arg.SubmissionUri,
		arg.Category,
		arg.Tags,
		arg.AutoTmm,
		arg.NameOverridden,
		arg.CloudFolder,
		arg.SavePath,
		arg.DestinationName,
		arg.CloudTaskName,
		arg.CloudResultPath,
		arg.CopySourcePath,
		arg.ContentPath,
		arg.IsMultiFile,
		arg.TotalSize,
		arg.State,
		arg.OfflineProgress,
		arg.CopyProgress,
		arg.QbitProgress,
		arg.LastUpstreamStatus,
		arg.PhaseStartedAt,
		arg.OfflineStartedAt,
		arg.CopyCompletedAt,
		arg.NextRunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Hash,
	)
	return err
}

const setDownloadCategory = `-- name: SetDownloadCategory :execrows
UPDATE downloads
SET
    category = ?1,
    updated_at = ?2,
    row_version = row_version + 1
WHERE hash = ?3
`

type SetDownloadCategoryParams struct {
	Category  string    `json:"category"`
	UpdatedAt time.Time `json:"updated_at"`
	Hash      string    `json:"hash"`
}

func (q *Queries) SetDownloadCategory(ctx context.Context, arg SetDownloadCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setDownloadCategory, arg.Category, arg.UpdatedAt, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startDownload = `-- name: StartDownload :execrows
UPDATE downloads
SET
    state = CASE
        WHEN cloud_result_path IS NOT NULL
             AND (content_path IS NOT NULL OR last_upstream_status IN ('copy:COMPLETED', 'revive:retained_content'))
        THEN 'VERIFYING_LOCAL'
        WHEN cloud_result_path IS NOT NULL
        THEN 'SUBMITTING_COPY'
        ELSE 'ACCEPTED'
    END,
    pause_requested = 0,
    phase_started_at = ?1,
    next_run_at = ?1,
    lease_until = NULL,
    lease_owner = NULL,
    updated_at = ?1,
    row_version = row_version + 1
WHERE hash = ?2
  AND state = 'STOPPED'
`

type StartDownloadParams struct {
	Now  time.Time `json:"now"`
	Hash string    `json:"hash"`
}

func (q *Queries) StartDownload(ctx context.Context, arg StartDownloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startDownload, arg.Now, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
