// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
	"time"
)

type ApiToken struct {
	ID          int64     `json:"id"`
	TokenHash   []byte    `json:"token_hash"`
	TokenHint   string    `json:"token_hint"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	RowVersion  int64     `json:"row_version"`
	TokenSecret string    `json:"token_secret"`
}

type Category struct {
	Name      string    `json:"name"`
	CloudPath string    `json:"cloud_path"`
	SavePath  string    `json:"save_path"`
	Enabled   int64     `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DomainEvent struct {
	Sequence         int64     `json:"sequence"`
	ID               string    `json:"id"`
	Type             string    `json:"type"`
	AggregateType    string    `json:"aggregate_type"`
	AggregateID      string    `json:"aggregate_id"`
	AggregateVersion int64     `json:"aggregate_version"`
	Payload          []byte    `json:"payload"`
	OccurredAt       time.Time `json:"occurred_at"`
}

type Download struct {
	Hash                 string         `json:"hash"`
	Name                 string         `json:"name"`
	SourceKind           string         `json:"source_kind"`
	SubmissionUri        string         `json:"submission_uri"`
	Category             string         `json:"category"`
	CloudFolder          string         `json:"cloud_folder"`
	SavePath             string         `json:"save_path"`
	DestinationName      sql.NullString `json:"destination_name"`
	CloudTaskName        sql.NullString `json:"cloud_task_name"`
	CloudSourcePath      sql.NullString `json:"cloud_source_path"`
	ContentPath          sql.NullString `json:"content_path"`
	IsMultiFile          sql.NullInt64  `json:"is_multi_file"`
	TotalSize            int64          `json:"total_size"`
	State                string         `json:"state"`
	OfflineProgress      float64        `json:"offline_progress"`
	CopyProgress         float64        `json:"copy_progress"`
	QbitProgress         float64        `json:"qbit_progress"`
	LastUpstreamStatus   sql.NullString `json:"last_upstream_status"`
	LastError            sql.NullString `json:"last_error"`
	PhaseStartedAt       time.Time      `json:"phase_started_at"`
	NextRunAt            sql.NullTime   `json:"next_run_at"`
	LeaseUntil           sql.NullTime   `json:"lease_until"`
	LeaseOwner           sql.NullString `json:"lease_owner"`
	AttemptCount         int64          `json:"attempt_count"`
	DeleteFilesRequested int64          `json:"delete_files_requested"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	CompletedAt          sql.NullTime   `json:"completed_at"`
	RemovedAt            sql.NullTime   `json:"removed_at"`
	RowVersion           int64          `json:"row_version"`
	PauseRequested       int64          `json:"pause_requested"`
	LastErrorCode        sql.NullString `json:"last_error_code"`
}

type DownloadFile struct {
	DownloadHash string `json:"download_hash"`
	FileIndex    int64  `json:"file_index"`
	RelativePath string `json:"relative_path"`
	Size         int64  `json:"size"`
}

type OperatorPassword struct {
	ID           int64     `json:"id"`
	PasswordHash string    `json:"password_hash"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type QbtApiKey struct {
	ID         int64     `json:"id"`
	KeyHash    []byte    `json:"key_hash"`
	KeyHint    string    `json:"key_hint"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	Active     int64     `json:"active"`
	RowVersion int64     `json:"row_version"`
	KeySecret  string    `json:"key_secret"`
}

type Session struct {
	SidDigest []byte    `json:"sid_digest"`
	CsrfToken string    `json:"csrf_token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Setting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WebhookDelivery struct {
	ID             int64          `json:"id"`
	EventID        string         `json:"event_id"`
	EndpointID     int64          `json:"endpoint_id"`
	EndpointName   string         `json:"endpoint_name"`
	EventType      string         `json:"event_type"`
	AggregateType  string         `json:"aggregate_type"`
	AggregateID    string         `json:"aggregate_id"`
	Status         string         `json:"status"`
	AttemptCount   int64          `json:"attempt_count"`
	FirstAttemptAt sql.NullTime   `json:"first_attempt_at"`
	NextAttemptAt  sql.NullTime   `json:"next_attempt_at"`
	LeaseOwner     sql.NullString `json:"lease_owner"`
	LeaseUntil     sql.NullTime   `json:"lease_until"`
	LastHttpStatus sql.NullInt64  `json:"last_http_status"`
	LastError      sql.NullString `json:"last_error"`
	DeliveredAt    sql.NullTime   `json:"delivered_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	RowVersion     int64          `json:"row_version"`
}

type WebhookEndpoint struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Url         string         `json:"url"`
	HmacSecret  string         `json:"hmac_secret"`
	BearerToken sql.NullString `json:"bearer_token"`
	Enabled     int64          `json:"enabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	RowVersion  int64          `json:"row_version"`
}

type WebhookSubscription struct {
	EndpointID int64  `json:"endpoint_id"`
	EventType  string `json:"event_type"`
}
