// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operator.sql

package storedb

import (
	"context"
	"time"
)

const getOperatorPassword = `-- name: GetOperatorPassword :one
SELECT password_hash FROM operator_password WHERE id = 1
`

func (q *Queries) GetOperatorPassword(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getOperatorPassword)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const upsertOperatorPassword = `-- name: UpsertOperatorPassword :exec
INSERT INTO operator_password (id, password_hash, updated_at)
VALUES (1, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    password_hash = excluded.password_hash,
    updated_at = excluded.updated_at
`

type UpsertOperatorPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) UpsertOperatorPassword(ctx context.Context, arg UpsertOperatorPasswordParams) error {
	_, err := q.db.ExecContext(ctx, upsertOperatorPassword, arg.PasswordHash, arg.UpdatedAt)
	return err
}
