// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package storedb

import (
	"context"
	"database/sql"
	"time"
)

const cancelEndpointDeliveries = `-- name: CancelEndpointDeliveries :exec
UPDATE webhook_deliveries
SET
    status = 'cancelled',
    next_attempt_at = NULL,
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = ?1,
    row_version = row_version + 1
WHERE endpoint_id = ?2
  AND status IN ('pending', 'dead')
`

type CancelEndpointDeliveriesParams struct {
	UpdatedAt  time.Time `json:"updated_at"`
	EndpointID int64     `json:"endpoint_id"`
}

func (q *Queries) CancelEndpointDeliveries(ctx context.Context, arg CancelEndpointDeliveriesParams) error {
	_, err := q.db.ExecContext(ctx, cancelEndpointDeliveries, arg.UpdatedAt, arg.EndpointID)
	return err
}

const cancelSubscriptionDeliveries = `-- name: CancelSubscriptionDeliveries :exec
UPDATE webhook_deliveries
SET
    status = 'cancelled',
    next_attempt_at = NULL,
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = ?1,
    row_version = row_version + 1
WHERE endpoint_id = ?2
  AND event_type = ?3
  AND status IN ('pending', 'dead')
`

type CancelSubscriptionDeliveriesParams struct {
	UpdatedAt  time.Time `json:"updated_at"`
	EndpointID int64     `json:"endpoint_id"`
	EventType  string    `json:"event_type"`
}

func (q *Queries) CancelSubscriptionDeliveries(ctx context.Context, arg CancelSubscriptionDeliveriesParams) error {
	_, err := q.db.ExecContext(ctx, cancelSubscriptionDeliveries, arg.UpdatedAt, arg.EndpointID, arg.EventType)
	return err
}

const claimWebhookDue = `-- name: ClaimWebhookDue :one
UPDATE webhook_deliveries
SET
    status = 'delivering',
    attempt_count = attempt_count + 1,
    first_attempt_at = COALESCE(first_attempt_at, ?1),
    lease_owner = ?2,
    lease_until = ?3,
    updated_at = ?1,
    row_version = row_version + 1
WHERE id = (
    SELECT candidate.id
    FROM webhook_deliveries AS candidate
    JOIN webhook_endpoints AS endpoint ON endpoint.id = candidate.endpoint_id
    WHERE candidate.status IN ('pending', 'delivering')
      AND candidate.next_attempt_at <= ?1
      AND (candidate.lease_until IS NULL OR candidate.lease_until <= ?1)
      AND endpoint.enabled = 1
      AND endpoint.deleted_at IS NULL
      AND NOT EXISTS (
          SELECT 1
          FROM webhook_deliveries AS earlier
          WHERE earlier.endpoint_id = candidate.endpoint_id
            AND earlier.aggregate_type = candidate.aggregate_type
            AND earlier.aggregate_id = candidate.aggregate_id
            AND earlier.status IN ('pending', 'delivering')
            AND (
                earlier.created_at < candidate.created_at
                OR (earlier.created_at = candidate.created_at AND earlier.id < candidate.id)
            )
      )
    ORDER BY candidate.next_attempt_at ASC, candidate.created_at ASC, candidate.id ASC
    LIMIT 1
)
RETURNING id, event_id, endpoint_id, endpoint_name, event_type, aggregate_type, aggregate_id, status, attempt_count, first_attempt_at, next_attempt_at, lease_owner, lease_until, last_http_status, last_error, delivered_at, created_at, updated_at, row_version
`

type ClaimWebhookDueParams struct {
	Now        time.Time      `json:"now"`
	Owner      sql.NullString `json:"owner"`
	LeaseUntil sql.NullTime   `json:"lease_until"`
}

func (q *Queries) ClaimWebhookDue(ctx context.Context, arg ClaimWebhookDueParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, claimWebhookDue, arg.Now, arg.Owner, arg.LeaseUntil)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.EndpointName,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Status,
		&i.AttemptCount,
		&i.FirstAttemptAt,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastHttpStatus,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const commitWebhookClaim = `-- name: CommitWebhookClaim :execrows
UPDATE webhook_deliveries
SET
    status = ?1,
    last_http_status = ?2,
    last_error = ?3,
    next_attempt_at = ?4,
    delivered_at = ?5,
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = ?6,
    row_version = row_version + 1
WHERE id = ?7
  AND status = 'delivering'
  AND lease_owner = ?8
  AND row_version = ?9
`

type CommitWebhookClaimParams struct {
	Status             string         `json:"status"`
	LastHttpStatus     sql.NullInt64  `json:"last_http_status"`
	LastError          sql.NullString `json:"last_error"`
	NextAttemptAt      sql.NullTime   `json:"next_attempt_at"`
	DeliveredAt        sql.NullTime   `json:"delivered_at"`
	Now                time.Time      `json:"now"`
	ID                 int64          `json:"id"`
	LeaseOwner         sql.NullString `json:"lease_owner"`
	ExpectedRowVersion int64          `json:"expected_row_version"`
}

func (q *Queries) CommitWebhookClaim(ctx context.Context, arg CommitWebhookClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, commitWebhookClaim,
		arg.Status,
		arg.LastHttpStatus,
		arg.LastError,
		arg.NextAttemptAt,
		arg.DeliveredAt,
		arg.Now,
		arg.ID,
		arg.LeaseOwner,
		arg.ExpectedRowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEndpoint = `-- name: DeleteEndpoint :execrows
UPDATE webhook_endpoints
SET
    enabled = 0,
    deleted_at = ?1,
    updated_at = ?2,
    row_version = row_version + 1
WHERE id = ?3
  AND deleted_at IS NULL
`

type DeleteEndpointParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        int64        `json:"id"`
}

func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEndpoint, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM webhook_subscriptions
WHERE endpoint_id = ?1
  AND event_type = ?2
`

type DeleteSubscriptionParams struct {
	EndpointID int64  `json:"endpoint_id"`
	EventType  string `json:"event_type"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, arg.EndpointID, arg.EventType)
	return err
}

const endpointExists = `-- name: EndpointExists :one
SELECT EXISTS(SELECT 1 FROM webhook_endpoints WHERE id = ?1)
`

func (q *Queries) EndpointExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, endpointExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, event_id, endpoint_id, endpoint_name, event_type, aggregate_type, aggregate_id, status, attempt_count, first_attempt_at, next_attempt_at, lease_owner, lease_until, last_http_status, last_error, delivered_at, created_at, updated_at, row_version
FROM webhook_deliveries
WHERE id = ?1
`

func (q *Queries) GetDelivery(ctx context.Context, id int64) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, getDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.EndpointName,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Status,
		&i.AttemptCount,
		&i.FirstAttemptAt,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastHttpStatus,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, name, url, hmac_secret, bearer_token, enabled, created_at, updated_at, deleted_at, row_version
FROM webhook_endpoints
WHERE id = ?1
  AND deleted_at IS NULL
`

func (q *Queries) GetEndpoint(ctx context.Context, id int64) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getEndpoint, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.HmacSecret,
		&i.BearerToken,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return i, err
}

const getEndpointDeletedAt = `-- name: GetEndpointDeletedAt :one
SELECT deleted_at
FROM webhook_endpoints
WHERE id = ?1
`

func (q *Queries) GetEndpointDeletedAt(ctx context.Context, id int64) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getEndpointDeletedAt, id)
	var deleted_at sql.NullTime
	err := row.Scan(&deleted_at)
	return deleted_at, err
}

const getEndpointRaw = `-- name: GetEndpointRaw :one
SELECT id, name, url, hmac_secret, bearer_token, enabled, created_at, updated_at, deleted_at, row_version
FROM webhook_endpoints
WHERE id = ?1
`

func (q *Queries) GetEndpointRaw(ctx context.Context, id int64) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getEndpointRaw, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.HmacSecret,
		&i.BearerToken,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return i, err
}

const getEndpointSubscriptions = `-- name: GetEndpointSubscriptions :many
SELECT event_type
FROM webhook_subscriptions
WHERE endpoint_id = ?1
ORDER BY event_type ASC
`

func (q *Queries) GetEndpointSubscriptions(ctx context.Context, endpointID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEndpointSubscriptions, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var event_type string
		if err := rows.Scan(&event_type); err != nil {
			return nil, err
		}
		items = append(items, event_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, type, aggregate_type, aggregate_id, aggregate_version, payload, occurred_at
FROM domain_events
WHERE id = ?1
`

func (q *Queries) GetEvent(ctx context.Context, id string) (DomainEvent, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i DomainEvent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.OccurredAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :one
INSERT INTO webhook_deliveries (
    event_id,
    endpoint_id,
    endpoint_name,
    event_type,
    aggregate_type,
    aggregate_id,
    status,
    next_attempt_at,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    'pending',
    ?7,
    ?8,
    ?9
)
RETURNING id, event_id, endpoint_id, endpoint_name, event_type, aggregate_type, aggregate_id, status, attempt_count, first_attempt_at, next_attempt_at, lease_owner, lease_until, last_http_status, last_error, delivered_at, created_at, updated_at, row_version
`

type InsertDeliveryParams struct {
	EventID       string       `json:"event_id"`
	EndpointID    int64        `json:"endpoint_id"`
	EndpointName  string       `json:"endpoint_name"`
	EventType     string       `json:"event_type"`
	AggregateType string       `json:"aggregate_type"`
	AggregateID   string       `json:"aggregate_id"`
	NextAttemptAt sql.NullTime `json:"next_attempt_at"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, insertDelivery,
		arg.EventID,
		arg.EndpointID,
		arg.EndpointName,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.NextAttemptAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.EndpointName,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Status,
		&i.AttemptCount,
		&i.FirstAttemptAt,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastHttpStatus,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const insertEndpoint = `-- name: InsertEndpoint :one
INSERT INTO webhook_endpoints (
    name,
    url,
    hmac_secret,
    bearer_token,
    enabled,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
RETURNING id, name, url, hmac_secret, bearer_token, enabled, created_at, updated_at, deleted_at, row_version
`

type InsertEndpointParams struct {
	Name        string         `json:"name"`
	Url         string         `json:"url"`
	HmacSecret  string         `json:"hmac_secret"`
	BearerToken sql.NullString `json:"bearer_token"`
	Enabled     int64          `json:"enabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) InsertEndpoint(ctx context.Context, arg InsertEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, insertEndpoint,
		arg.Name,
		arg.Url,
		arg.HmacSecret,
		arg.BearerToken,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.HmacSecret,
		&i.BearerToken,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO domain_events (
    id,
    type,
    aggregate_type,
    aggregate_id,
    aggregate_version,
    payload,
    occurred_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
`

type InsertEventParams struct {
	ID               string    `json:"id"`
	Type             string    `json:"type"`
	AggregateType    string    `json:"aggregate_type"`
	AggregateID      string    `json:"aggregate_id"`
	AggregateVersion int64     `json:"aggregate_version"`
	Payload          []byte    `json:"payload"`
	OccurredAt       time.Time `json:"occurred_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.Type,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO webhook_subscriptions (
    endpoint_id,
    event_type
) VALUES (
    ?1,
    ?2
)
`

type InsertSubscriptionParams struct {
	EndpointID int64  `json:"endpoint_id"`
	EventType  string `json:"event_type"`
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, insertSubscription, arg.EndpointID, arg.EventType)
	return err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, event_id, endpoint_id, endpoint_name, event_type, aggregate_type, aggregate_id, status, attempt_count, first_attempt_at, next_attempt_at, lease_owner, lease_until, last_http_status, last_error, delivered_at, created_at, updated_at, row_version
FROM webhook_deliveries
WHERE endpoint_id = COALESCE(?1, endpoint_id)
  AND event_type = COALESCE(?2, event_type)
  AND status = COALESCE(?3, status)
  AND (
      created_at < ?4
      OR (created_at = ?4 AND id < ?5)
      OR ?5 < 0
  )
ORDER BY created_at DESC, id DESC
LIMIT ?6
`

type ListDeliveriesParams struct {
	EndpointID sql.NullInt64  `json:"endpoint_id"`
	EventType  sql.NullString `json:"event_type"`
	Status     sql.NullString `json:"status"`
	CursorTime sql.NullTime   `json:"cursor_time"`
	CursorID   int64          `json:"cursor_id"`
	Limit      int64          `json:"limit"`
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveries,
		arg.EndpointID,
		arg.EventType,
		arg.Status,
		arg.CursorTime,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.EndpointName,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Status,
			&i.AttemptCount,
			&i.FirstAttemptAt,
			&i.NextAttemptAt,
			&i.LeaseOwner,
			&i.LeaseUntil,
			&i.LastHttpStatus,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointSubscriptions = `-- name: ListEndpointSubscriptions :many
SELECT endpoint_id, event_type
FROM webhook_subscriptions
ORDER BY endpoint_id ASC, event_type ASC
`

func (q *Queries) ListEndpointSubscriptions(ctx context.Context) ([]WebhookSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listEndpointSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(&i.EndpointID, &i.EventType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, name, url, hmac_secret, bearer_token, enabled, created_at, updated_at, deleted_at, row_version
FROM webhook_endpoints
WHERE deleted_at IS NULL
ORDER BY name COLLATE NOCASE ASC, id ASC
`

func (q *Queries) ListEndpoints(ctx context.Context) ([]WebhookEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.HmacSecret,
			&i.BearerToken,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RowVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByAggregate = `-- name: ListEventsByAggregate :many
SELECT id, type, aggregate_type, aggregate_id, aggregate_version, payload, occurred_at
FROM domain_events
WHERE aggregate_type = ?1
  AND aggregate_id = ?2
ORDER BY occurred_at ASC, id ASC
`

type ListEventsByAggregateParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
}

func (q *Queries) ListEventsByAggregate(ctx context.Context, arg ListEventsByAggregateParams) ([]DomainEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByAggregate, arg.AggregateType, arg.AggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainEvent{}
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AggregateType,
			&i.AggregateID,
			&i.AggregateVersion,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribedEndpoints = `-- name: ListSubscribedEndpoints :many
SELECT endpoint.id, endpoint.name
FROM webhook_endpoints AS endpoint
JOIN webhook_subscriptions AS subscription ON subscription.endpoint_id = endpoint.id
WHERE subscription.event_type = ?1
  AND endpoint.enabled = 1
  AND endpoint.deleted_at IS NULL
ORDER BY endpoint.id ASC
`

type ListSubscribedEndpointsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListSubscribedEndpoints(ctx context.Context, eventType string) ([]ListSubscribedEndpointsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscribedEndpoints, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscribedEndpointsRow{}
	for rows.Next() {
		var i ListSubscribedEndpointsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextWebhookDue = `-- name: NextWebhookDue :one
SELECT effective_due.next_due
FROM (
    SELECT candidate.next_attempt_at AS next_due
    FROM webhook_deliveries AS candidate
    JOIN webhook_endpoints AS endpoint ON endpoint.id = candidate.endpoint_id
    WHERE candidate.status IN ('pending', 'delivering')
      AND candidate.next_attempt_at IS NOT NULL
      AND endpoint.enabled = 1
      AND endpoint.deleted_at IS NULL
      AND (
          candidate.lease_until IS NULL
          OR candidate.lease_until <= ?1
          OR candidate.lease_until <= candidate.next_attempt_at
      )
      AND NOT EXISTS (
          SELECT 1
          FROM webhook_deliveries AS earlier
          WHERE earlier.endpoint_id = candidate.endpoint_id
            AND earlier.aggregate_type = candidate.aggregate_type
            AND earlier.aggregate_id = candidate.aggregate_id
            AND earlier.status IN ('pending', 'delivering')
            AND (
                earlier.created_at < candidate.created_at
                OR (earlier.created_at = candidate.created_at AND earlier.id < candidate.id)
            )
      )

    UNION ALL

    SELECT candidate.lease_until AS next_due
    FROM webhook_deliveries AS candidate
    JOIN webhook_endpoints AS endpoint ON endpoint.id = candidate.endpoint_id
    WHERE candidate.status IN ('pending', 'delivering')
      AND candidate.next_attempt_at IS NOT NULL
      AND endpoint.enabled = 1
      AND endpoint.deleted_at IS NULL
      AND candidate.lease_until > ?1
      AND candidate.lease_until > candidate.next_attempt_at
      AND NOT EXISTS (
          SELECT 1
          FROM webhook_deliveries AS earlier
          WHERE earlier.endpoint_id = candidate.endpoint_id
            AND earlier.aggregate_type = candidate.aggregate_type
            AND earlier.aggregate_id = candidate.aggregate_id
            AND earlier.status IN ('pending', 'delivering')
            AND (
                earlier.created_at < candidate.created_at
                OR (earlier.created_at = candidate.created_at AND earlier.id < candidate.id)
            )
      )
) AS effective_due
ORDER BY effective_due.next_due ASC
LIMIT 1
`

func (q *Queries) NextWebhookDue(ctx context.Context, now sql.NullTime) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, nextWebhookDue, now)
	var next_due sql.NullTime
	err := row.Scan(&next_due)
	return next_due, err
}

const pruneDeliveries = `-- name: PruneDeliveries :execrows
DELETE FROM webhook_deliveries
WHERE status IN ('succeeded', 'cancelled')
  AND updated_at < ?1
`

func (q *Queries) PruneDeliveries(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneDeliveries, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const replayDelivery = `-- name: ReplayDelivery :one
UPDATE webhook_deliveries
SET
    status = 'pending',
    attempt_count = 0,
    first_attempt_at = NULL,
    next_attempt_at = ?1,
    lease_owner = NULL,
    lease_until = NULL,
    last_http_status = NULL,
    last_error = NULL,
    delivered_at = NULL,
    updated_at = ?1,
    row_version = row_version + 1
WHERE webhook_deliveries.id = ?2
  AND status = 'dead'
  AND endpoint_id IN (
      SELECT endpoint.id
      FROM webhook_endpoints AS endpoint
      WHERE endpoint.enabled = 1 AND endpoint.deleted_at IS NULL
  )
RETURNING id, event_id, endpoint_id, endpoint_name, event_type, aggregate_type, aggregate_id, status, attempt_count, first_attempt_at, next_attempt_at, lease_owner, lease_until, last_http_status, last_error, delivered_at, created_at, updated_at, row_version
`

type ReplayDeliveryParams struct {
	Now sql.NullTime `json:"now"`
	ID  int64        `json:"id"`
}

func (q *Queries) ReplayDelivery(ctx context.Context, arg ReplayDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, replayDelivery, arg.Now, arg.ID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.EndpointName,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Status,
		&i.AttemptCount,
		&i.FirstAttemptAt,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LastHttpStatus,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const rotateEndpointSecret = `-- name: RotateEndpointSecret :one
UPDATE webhook_endpoints
SET
    hmac_secret = ?1,
    updated_at = ?2,
    row_version = row_version + 1
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id, name, url, hmac_secret, bearer_token, enabled, created_at, updated_at, deleted_at, row_version
`

type RotateEndpointSecretParams struct {
	HmacSecret string    `json:"hmac_secret"`
	UpdatedAt  time.Time `json:"updated_at"`
	ID         int64     `json:"id"`
}

func (q *Queries) RotateEndpointSecret(ctx context.Context, arg RotateEndpointSecretParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, rotateEndpointSecret, arg.HmacSecret, arg.UpdatedAt, arg.ID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.HmacSecret,
		&i.BearerToken,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return i, err
}

const setEndpointEnabled = `-- name: SetEndpointEnabled :execrows
UPDATE webhook_endpoints
SET
    enabled = ?1,
    updated_at = ?2,
    row_version = row_version + 1
WHERE id = ?3
  AND deleted_at IS NULL
`

type SetEndpointEnabledParams struct {
	Enabled   int64     `json:"enabled"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        int64     `json:"id"`
}

func (q *Queries) SetEndpointEnabled(ctx context.Context, arg SetEndpointEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setEndpointEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE webhook_endpoints
SET
    name = ?1,
    url = ?2,
    bearer_token = ?3,
    enabled = ?4,
    updated_at = ?5,
    row_version = row_version + 1
WHERE id = ?6
  AND deleted_at IS NULL
RETURNING id, name, url, hmac_secret, bearer_token, enabled, created_at, updated_at, deleted_at, row_version
`

type UpdateEndpointParams struct {
	Name        string         `json:"name"`
	Url         string         `json:"url"`
	BearerToken sql.NullString `json:"bearer_token"`
	Enabled     int64          `json:"enabled"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, updateEndpoint,
		arg.Name,
		arg.Url,
		arg.BearerToken,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.HmacSecret,
		&i.BearerToken,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RowVersion,
	)
	return i, err
}
