// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qbt_compat.sql

package storedb

import (
	"context"
	"time"
)

const deleteDownloadFileOverride = `-- name: DeleteDownloadFileOverride :exec
DELETE FROM download_file_overrides
WHERE download_hash = ?1 AND file_index = ?2
`

type DeleteDownloadFileOverrideParams struct {
	DownloadHash string `json:"download_hash"`
	FileIndex    int64  `json:"file_index"`
}

func (q *Queries) DeleteDownloadFileOverride(ctx context.Context, arg DeleteDownloadFileOverrideParams) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadFileOverride, arg.DownloadHash, arg.FileIndex)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT "key", value, updated_at FROM settings WHERE key = ?1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i Setting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listDownloadFileOverrides = `-- name: ListDownloadFileOverrides :many
SELECT download_hash, file_index, relative_path, priority FROM download_file_overrides
WHERE download_hash = ?1
ORDER BY file_index ASC
`

func (q *Queries) ListDownloadFileOverrides(ctx context.Context, downloadHash string) ([]DownloadFileOverride, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadFileOverrides, downloadHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadFileOverride{}
	for rows.Next() {
		var i DownloadFileOverride
		if err := rows.Scan(
			&i.DownloadHash,
			&i.FileIndex,
			&i.RelativePath,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDownloadName = `-- name: SetDownloadName :execrows
UPDATE downloads SET name = ?1, updated_at = ?2, row_version = row_version + 1
WHERE hash = ?3 AND state != 'DELETED'
`

type SetDownloadNameParams struct {
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	Hash      string    `json:"hash"`
}

func (q *Queries) SetDownloadName(ctx context.Context, arg SetDownloadNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setDownloadName, arg.Name, arg.UpdatedAt, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchDownload = `-- name: TouchDownload :execrows
UPDATE downloads SET updated_at = ?1, row_version = row_version + 1
WHERE hash = ?2 AND state != 'DELETED'
`

type TouchDownloadParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	Hash      string    `json:"hash"`
}

func (q *Queries) TouchDownload(ctx context.Context, arg TouchDownloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchDownload, arg.UpdatedAt, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDownloadAutoTMM = `-- name: UpdateDownloadAutoTMM :execrows
UPDATE downloads SET auto_tmm = ?1, updated_at = ?2, row_version = row_version + 1
WHERE hash = ?3 AND state != 'DELETED'
`

type UpdateDownloadAutoTMMParams struct {
	AutoTmm   int64     `json:"auto_tmm"`
	UpdatedAt time.Time `json:"updated_at"`
	Hash      string    `json:"hash"`
}

func (q *Queries) UpdateDownloadAutoTMM(ctx context.Context, arg UpdateDownloadAutoTMMParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDownloadAutoTMM, arg.AutoTmm, arg.UpdatedAt, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDownloadSavePath = `-- name: UpdateDownloadSavePath :execrows
UPDATE downloads SET save_path = ?1, updated_at = ?2, row_version = row_version + 1
WHERE hash = ?3 AND state IN ('STOPPED', 'ACCEPTED') AND lease_owner IS NULL AND content_path IS NULL AND copy_source_path IS NULL AND cloud_result_path IS NULL AND row_version = ?4
`

type UpdateDownloadSavePathParams struct {
	SavePath           string    `json:"save_path"`
	UpdatedAt          time.Time `json:"updated_at"`
	Hash               string    `json:"hash"`
	ExpectedRowVersion int64     `json:"expected_row_version"`
}

func (q *Queries) UpdateDownloadSavePath(ctx context.Context, arg UpdateDownloadSavePathParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDownloadSavePath,
		arg.SavePath,
		arg.UpdatedAt,
		arg.Hash,
		arg.ExpectedRowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDownloadTags = `-- name: UpdateDownloadTags :execrows
UPDATE downloads SET tags = ?1, updated_at = ?2, row_version = row_version + 1
WHERE hash = ?3 AND state != 'DELETED'
`

type UpdateDownloadTagsParams struct {
	Tags      string    `json:"tags"`
	UpdatedAt time.Time `json:"updated_at"`
	Hash      string    `json:"hash"`
}

func (q *Queries) UpdateDownloadTags(ctx context.Context, arg UpdateDownloadTagsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDownloadTags, arg.Tags, arg.UpdatedAt, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertDownloadFileOverride = `-- name: UpsertDownloadFileOverride :exec
INSERT INTO download_file_overrides (download_hash, file_index, relative_path, priority)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(download_hash, file_index) DO UPDATE SET
  relative_path = excluded.relative_path,
  priority = excluded.priority
`

type UpsertDownloadFileOverrideParams struct {
	DownloadHash string `json:"download_hash"`
	FileIndex    int64  `json:"file_index"`
	RelativePath string `json:"relative_path"`
	Priority     int64  `json:"priority"`
}

func (q *Queries) UpsertDownloadFileOverride(ctx context.Context, arg UpsertDownloadFileOverrideParams) error {
	_, err := q.db.ExecContext(ctx, upsertDownloadFileOverride,
		arg.DownloadHash,
		arg.FileIndex,
		arg.RelativePath,
		arg.Priority,
	)
	return err
}
