// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qbt_compat.sql

package storedb

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const clearDownloadCategories = `-- name: ClearDownloadCategories :execrows
UPDATE downloads
SET category = '', updated_at = ?1, row_version = row_version + 1
WHERE category IN (/*SLICE:names*/?)
  AND state != 'DELETED'
`

type ClearDownloadCategoriesParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	Names     []string  `json:"names"`
}

func (q *Queries) ClearDownloadCategories(ctx context.Context, arg ClearDownloadCategoriesParams) (int64, error) {
	query := clearDownloadCategories
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	if len(arg.Names) > 0 {
		for _, v := range arg.Names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(arg.Names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDownloadFileOverride = `-- name: DeleteDownloadFileOverride :exec
DELETE FROM download_file_overrides
WHERE download_hash = ?1 AND file_index = ?2
`

type DeleteDownloadFileOverrideParams struct {
	DownloadHash string `json:"download_hash"`
	FileIndex    int64  `json:"file_index"`
}

func (q *Queries) DeleteDownloadFileOverride(ctx context.Context, arg DeleteDownloadFileOverrideParams) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadFileOverride, arg.DownloadHash, arg.FileIndex)
	return err
}

const deleteQbtCategories = `-- name: DeleteQbtCategories :execrows
DELETE FROM categories
WHERE name IN (/*SLICE:names*/?)
`

func (q *Queries) DeleteQbtCategories(ctx context.Context, names []string) (int64, error) {
	query := deleteQbtCategories
	var queryParams []interface{}
	if len(names) > 0 {
		for _, v := range names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteQbtTag = `-- name: DeleteQbtTag :execrows
DELETE FROM qbt_tags WHERE name = ?1
`

func (q *Queries) DeleteQbtTag(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteQbtTag, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSetting = `-- name: GetSetting :one
SELECT "key", value, updated_at FROM settings WHERE key = ?1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i Setting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const insertQbtTag = `-- name: InsertQbtTag :execrows
INSERT INTO qbt_tags (name) VALUES (?1)
ON CONFLICT(name) DO NOTHING
`

func (q *Queries) InsertQbtTag(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertQbtTag, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDownloadFileOverrides = `-- name: ListDownloadFileOverrides :many
SELECT download_hash, file_index, relative_path, priority FROM download_file_overrides
WHERE download_hash = ?1
ORDER BY file_index ASC
`

func (q *Queries) ListDownloadFileOverrides(ctx context.Context, downloadHash string) ([]DownloadFileOverride, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadFileOverrides, downloadHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadFileOverride{}
	for rows.Next() {
		var i DownloadFileOverride
		if err := rows.Scan(
			&i.DownloadHash,
			&i.FileIndex,
			&i.RelativePath,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQbtTags = `-- name: ListQbtTags :many
SELECT name FROM qbt_tags ORDER BY name ASC
`

func (q *Queries) ListQbtTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listQbtTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reverifyDownload = `-- name: ReverifyDownload :execrows
UPDATE downloads
SET
    state = 'VERIFYING_LOCAL',
    last_error = NULL,
    last_error_code = NULL,
    attempt_count = 0,
    phase_started_at = ?1,
    next_run_at = ?1,
    lease_until = NULL,
    lease_owner = NULL,
    completed_at = NULL,
    updated_at = ?1,
    row_version = row_version + 1
WHERE hash = ?2
  AND state = 'COMPLETED'
`

type ReverifyDownloadParams struct {
	Now  time.Time `json:"now"`
	Hash string    `json:"hash"`
}

func (q *Queries) ReverifyDownload(ctx context.Context, arg ReverifyDownloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reverifyDownload, arg.Now, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setDownloadName = `-- name: SetDownloadName :execrows
UPDATE downloads SET name = ?1, name_overridden = 1, updated_at = ?2, row_version = row_version + 1
WHERE hash = ?3 AND state != 'DELETED'
`

type SetDownloadNameParams struct {
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	Hash      string    `json:"hash"`
}

func (q *Queries) SetDownloadName(ctx context.Context, arg SetDownloadNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setDownloadName, arg.Name, arg.UpdatedAt, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchDownload = `-- name: TouchDownload :execrows
UPDATE downloads SET updated_at = ?1, row_version = row_version + 1
WHERE hash = ?2 AND state != 'DELETED'
`

type TouchDownloadParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	Hash      string    `json:"hash"`
}

func (q *Queries) TouchDownload(ctx context.Context, arg TouchDownloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchDownload, arg.UpdatedAt, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCompletedDownloadContentPath = `-- name: UpdateCompletedDownloadContentPath :execrows
UPDATE downloads SET content_path = ?1, updated_at = ?2, row_version = row_version + 1
WHERE hash = ?3 AND state = 'COMPLETED'
`

type UpdateCompletedDownloadContentPathParams struct {
	ContentPath sql.NullString `json:"content_path"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Hash        string         `json:"hash"`
}

func (q *Queries) UpdateCompletedDownloadContentPath(ctx context.Context, arg UpdateCompletedDownloadContentPathParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCompletedDownloadContentPath, arg.ContentPath, arg.UpdatedAt, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDownloadAutoTMM = `-- name: UpdateDownloadAutoTMM :execrows
UPDATE downloads SET auto_tmm = ?1, updated_at = ?2, row_version = row_version + 1
WHERE hash = ?3 AND state != 'DELETED'
`

type UpdateDownloadAutoTMMParams struct {
	AutoTmm   int64     `json:"auto_tmm"`
	UpdatedAt time.Time `json:"updated_at"`
	Hash      string    `json:"hash"`
}

func (q *Queries) UpdateDownloadAutoTMM(ctx context.Context, arg UpdateDownloadAutoTMMParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDownloadAutoTMM, arg.AutoTmm, arg.UpdatedAt, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDownloadSavePath = `-- name: UpdateDownloadSavePath :execrows
UPDATE downloads SET save_path = ?1, workspace_path = ?2, updated_at = ?3, row_version = row_version + 1
WHERE hash = ?4 AND state IN ('STOPPED', 'ACCEPTED') AND lease_owner IS NULL AND content_path IS NULL AND copy_source_path IS NULL AND cloud_result_path IS NULL AND row_version = ?5
`

type UpdateDownloadSavePathParams struct {
	SavePath           string         `json:"save_path"`
	WorkspacePath      sql.NullString `json:"workspace_path"`
	UpdatedAt          time.Time      `json:"updated_at"`
	Hash               string         `json:"hash"`
	ExpectedRowVersion int64          `json:"expected_row_version"`
}

func (q *Queries) UpdateDownloadSavePath(ctx context.Context, arg UpdateDownloadSavePathParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDownloadSavePath,
		arg.SavePath,
		arg.WorkspacePath,
		arg.UpdatedAt,
		arg.Hash,
		arg.ExpectedRowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDownloadTags = `-- name: UpdateDownloadTags :execrows
UPDATE downloads SET tags = ?1, updated_at = ?2, row_version = row_version + 1
WHERE hash = ?3 AND state != 'DELETED'
`

type UpdateDownloadTagsParams struct {
	Tags      string    `json:"tags"`
	UpdatedAt time.Time `json:"updated_at"`
	Hash      string    `json:"hash"`
}

func (q *Queries) UpdateDownloadTags(ctx context.Context, arg UpdateDownloadTagsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDownloadTags, arg.Tags, arg.UpdatedAt, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertDownloadFileOverride = `-- name: UpsertDownloadFileOverride :exec
INSERT INTO download_file_overrides (download_hash, file_index, relative_path, priority)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(download_hash, file_index) DO UPDATE SET
  relative_path = excluded.relative_path,
  priority = excluded.priority
`

type UpsertDownloadFileOverrideParams struct {
	DownloadHash string `json:"download_hash"`
	FileIndex    int64  `json:"file_index"`
	RelativePath string `json:"relative_path"`
	Priority     int64  `json:"priority"`
}

func (q *Queries) UpsertDownloadFileOverride(ctx context.Context, arg UpsertDownloadFileOverrideParams) error {
	_, err := q.db.ExecContext(ctx, upsertDownloadFileOverride,
		arg.DownloadHash,
		arg.FileIndex,
		arg.RelativePath,
		arg.Priority,
	)
	return err
}
