// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qbt_api_key.sql

package storedb

import (
	"context"
	"time"
)

const activateQBTAPIKey = `-- name: ActivateQBTAPIKey :execrows
UPDATE qbt_api_key
SET
    key_hash = ?1,
    key_hint = ?2,
    key_secret = ?3,
    created_at = ?4,
    updated_at = ?5,
    active = 1,
    row_version = row_version + 1
WHERE id = 1
  AND active = 0
`

type ActivateQBTAPIKeyParams struct {
	KeyHash   []byte    `json:"key_hash"`
	KeyHint   string    `json:"key_hint"`
	KeySecret string    `json:"key_secret"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ActivateQBTAPIKey(ctx context.Context, arg ActivateQBTAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateQBTAPIKey,
		arg.KeyHash,
		arg.KeyHint,
		arg.KeySecret,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getQBTAPIKey = `-- name: GetQBTAPIKey :one
SELECT id, key_hash, key_hint, created_at, updated_at, active, row_version, key_secret
FROM qbt_api_key
WHERE id = 1
  AND active = 1
`

func (q *Queries) GetQBTAPIKey(ctx context.Context) (QbtApiKey, error) {
	row := q.db.QueryRowContext(ctx, getQBTAPIKey)
	var i QbtApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyHint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.RowVersion,
		&i.KeySecret,
	)
	return i, err
}

const insertQBTAPIKey = `-- name: InsertQBTAPIKey :exec
INSERT INTO qbt_api_key (
    id,
    key_hash,
    key_hint,
    key_secret,
    created_at,
    updated_at,
    active,
    row_version
) VALUES (
    1,
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    1,
    0
)
`

type InsertQBTAPIKeyParams struct {
	KeyHash   []byte    `json:"key_hash"`
	KeyHint   string    `json:"key_hint"`
	KeySecret string    `json:"key_secret"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertQBTAPIKey(ctx context.Context, arg InsertQBTAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertQBTAPIKey,
		arg.KeyHash,
		arg.KeyHint,
		arg.KeySecret,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const revokeQBTAPIKey = `-- name: RevokeQBTAPIKey :execrows
UPDATE qbt_api_key
SET
    active = 0,
    row_version = row_version + 1
WHERE id = 1
  AND active = 1
  AND row_version = ?1
`

func (q *Queries) RevokeQBTAPIKey(ctx context.Context, expectedRowVersion int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeQBTAPIKey, expectedRowVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
