// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package storedb

import (
	"context"
	"time"
)

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*)
FROM sessions
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const evictOldestSession = `-- name: EvictOldestSession :exec
DELETE FROM sessions
WHERE sid_digest = (
    SELECT sid_digest
    FROM sessions
    ORDER BY expires_at ASC, created_at ASC, sid_digest ASC
    LIMIT 1
)
`

func (q *Queries) EvictOldestSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, evictOldestSession)
	return err
}

const getSession = `-- name: GetSession :one
SELECT sid_digest, audience, csrf_token, created_at, expires_at
FROM sessions
WHERE sid_digest = ?1
  AND audience = ?2
`

type GetSessionParams struct {
	SidDigest []byte `json:"sid_digest"`
	Audience  string `json:"audience"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.SidDigest, arg.Audience)
	var i Session
	err := row.Scan(
		&i.SidDigest,
		&i.Audience,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (sid_digest, audience, csrf_token, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertSessionParams struct {
	SidDigest []byte    `json:"sid_digest"`
	Audience  string    `json:"audience"`
	CsrfToken string    `json:"csrf_token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.SidDigest,
		arg.Audience,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= ?1
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refreshSession = `-- name: RefreshSession :execrows
UPDATE sessions
SET expires_at = ?1
WHERE sid_digest = ?2
  AND audience = ?3
  AND expires_at = ?4
`

type RefreshSessionParams struct {
	NewExpiresAt      time.Time `json:"new_expires_at"`
	SidDigest         []byte    `json:"sid_digest"`
	Audience          string    `json:"audience"`
	ExpectedExpiresAt time.Time `json:"expected_expires_at"`
}

func (q *Queries) RefreshSession(ctx context.Context, arg RefreshSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refreshSession,
		arg.NewExpiresAt,
		arg.SidDigest,
		arg.Audience,
		arg.ExpectedExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSession = `-- name: RevokeSession :exec
DELETE FROM sessions
WHERE sid_digest = ?1
  AND audience = ?2
`

type RevokeSessionParams struct {
	SidDigest []byte `json:"sid_digest"`
	Audience  string `json:"audience"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.SidDigest, arg.Audience)
	return err
}
